In [ ]:
#we have to import the data set in colab note book
#we have to import pandas library
import pandas as pd #pd is nickname for pandas
df=pd.read_csv('Data.csv') #df is a variable which reads and stores the data which is available in csv file. pd is a function which reads the data. read_csv is a pre defined fuction which is have in python library.the file name is passes in parameters

In [ ]:
type(df)# which is used to check what is the type of data in ur file.

pandas.core.frame.DataFrame

In [ ]:
df #which print the stored the data in csv file

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
#step-2: grouping the input colomns and output colomns
x=df.iloc[ : , :-1]#iloc is fuction which is support the sclising operation.

In [ ]:
x

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [ ]:
y=df.iloc[:,-1]

In [ ]:
y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [ ]:
x=x.values # it converts the tabular format data into array format

In [ ]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
y=y.values  # it converts the tabular format data into array format

In [ ]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [ ]:
#step-3: handling the missing data or values.
#scenario-1: missing values in numeriacl colomn.
#calculate the mean or avarage of that colomn, and replace the empty values.
#scenario-2: missing values is non numerical colomns., which can be replaced with the highly repeated values.
#scenario-3:missing  values in huge data set.


import numpy as np
from sklearn.impute  import SimpleImputer  # it is a class which is uesd to replace missing values from sklearn .
imputer=SimpleImputer(missing_values=np.nan,strategy='mean') # imputer variable is created, where the nan value is replaced with the mean value and it is stored in imputer.
imputer.fit(x[:,1:3]) # for which colomns we want to apply the methods
x[:,1:3]=imputer.transform(x[:,1:3]) # the nan values are replaced with mean values

In [ ]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
# step-4: handling the catagorical data.
# which converts the text data into numarical data
from sklearn.preprocessing import OneHotEncoder # OneHotEncoder is class which was imported from sklearn.preprocessing. it is converts text code into binary code. OneHotEncoder is only used for input column.
from sklearn.compose import ColumnTransformer #ColomnTransfermer is a class which was imported from sklearn.compose.  ColomnTransefermer is a class is used to apply the changes of catagorical data into binary data

#Alexa-0,0,1

ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')   #encoder is a method which converts text to binary code.

x=ct.fit_transform(x)


In [ ]:
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder # import the label encoder library from sklear.preprocessing
le=LabelEncoder() # the  LabelEncoder is used to encode the output columns.
y=le.fit_transform(y)




In [ ]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
#step-5: split the data into training and testing the data
#we have to import the library from sklearn and selection
from sklearn.model_selection import train_test_split  # train_test_split is a class which was imported  from sklearn.model_selection. it was used for splinting the data training and testing.
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [ ]:
x_train

array([[0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [ ]:
x_test

array([[0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0]], dtype=object)

In [ ]:
y_train

array([1, 1, 0, 1, 1, 0, 0, 1])

In [ ]:
y_test

array([0, 0])

In [ ]:
#step-6:feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler() #we have created one object to class StanderdScaler
x_train[:,3:]=sc.fit_transform(x_train[:,3:])
x_test[ :,3:]=sc.transform(x_test[:,3:])


In [ ]:
x_train

array([[0.0, 1.0, 0.0, 0.017975032046140385, -0.2524749282526218],
       [1.0, 0.0, 0.0, 1.1683770829991251, 1.1738782746591003],
       [1.0, 0.0, 0.0, 0.5931760575226327, 0.5179640280646587],
       [0.0, 0.0, 1.0, -1.8514283007524597, -1.7308848174019988],
       [1.0, 0.0, 0.0, -0.701026249799475, -0.7938644651242248],
       [0.0, 1.0, 0.0, 1.4559775957373713, 1.54868641557021],
       [0.0, 0.0, 1.0, -0.2696254806921058, -0.5127583594408927],
       [1.0, 0.0, 0.0, -0.41342573706122887, 0.0494538519257717]],
      dtype=object)

In [ ]:
x_test

array([[0.0, 0.0, 1.0, -0.15778083684945438, -1.3560766764908891],
       [0.0, 1.0, 0.0, -1.4200275316450905, -1.1686726060353345]],
      dtype=object)

In [ ]:
#machine learning types:
#1.supervisioned learning: from the labeled data the ai-model should be predict or should classify the decision making
#2. un supervisioned learning: when the data set have un-labeled data,model remembers the pattrens of the data. we can perform predictions also by using the pattrens.
#3. rainforcement learning : it was a trail and error method, it learns from failures

#we used supervisioned learning ,in this there are two algorithums 1.linear regrestion algorithum, 2.logistic regrestion algorithum.
#logistic regrestion algorithum :when the model perform classification task we have apply the logistic regrestion algorithum.{ex:there have two outcomes like yes or no}
#Linear regrestion algorithum: when model perform prediction task we have to apply the linear regrestion algorithum. {ex: there have different outcome like different values}

#step-7:applying algorithum to the data and train the AI-model
from sklearn.linear_model import LogisticRegression #logistic regression class is imported by sklearn
Classifier=LogisticRegression()#create a variable called classifier and the LogisticRegression is used to train pour AI-model
Classifier.fit(x_train,y_train)

LogisticRegression()

In [ ]:
LogisticRegression()

LogisticRegression()

In [ ]:
y_pred=Classifier.predict([[1.0, 0.0, 0.0, -0.701026249799475, -0.7938644651242248]])

In [ ]:
y_pred

array([1])